import Head from "next/head";
import { useState } from "react";
import axios from "../config/axios";

export default function Home() {
  const nf = new Intl.NumberFormat("ID");

  const [result, setResult] = useState([]);
  const [param, setParam] = useState({
    jenis_kelamin: "Pria",
    usia: 0,
    perokok: "Ya",
    nominal: 0,
    lama_investasi: 0,
  });
  const handleinputUsia = (e) => {
    setParam((prevState) => ({
      ...prevState,
      usia: e.target.value,
    }));
  };
  const handleinputNominal = (e) => {
    setParam((prevState) => ({
      ...prevState,
      nominal: e.target.value,
    }));
  };
  const handleinputlamaInvest = (e) => {
    setParam((prevState) => ({
      ...prevState,
      lama_investasi: e.target.value,
    }));
  };
  const changeParam = (field, value) => {
    setParam((prevState) => ({
      ...prevState,
      [field]: value,
    }));
  };
  const _onSubmit = (e) => {
    e.preventDefault();
    if (param.lama_investasi == 0 || param.nominal == 0 || param.usia == 0) {
      window.alert("Pastikan Anda Mengisi Semua Data yang dibutuhkan");
    } else {
      axios
        .post("/invest", param)
        .then(({ data }) => {
          setResult(data.data);
          console.log(data.data);
        })
        .catch((error) => {
          window.alert("System bermasalah, Hubungi Admin");
          console.log(error);
        });
    }
  };
  return (
    <>
      <main className="d-flex flex-column min-vh-100">
        <Head>
          <title>Create Investasi App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="px-4 py-5 my-5 flex-grow-1">
          <div className="card">
            <h5 className="card-header">Investasi App</h5>
            <div className="card-body">
              <h5 className="card-title">Form Investasi</h5>
              <form>
                <div className="form-group">
                  <label htmlFor="formGroupExampleInput">Usia</label>
                  <input
                    className="form-control"
                    type="number"
                    value={param.usia}
                    onChange={(e) => handleinputUsia(e)}
                  ></input>{" "}
                </div>
                <div className="form-group">
                  <label htmlFor="formGroupExampleInput2">
                    Nominal Investasi
                  </label>
                  <input
                    className="form-control"
                    type="number"
                    value={param.nominal}
                    onChange={(e) => handleinputNominal(e)}
                  ></input>
                </div>
                <div className="form-group">
                  <label htmlFor="formGroupExampleInput2">Lama Investasi</label>
                  <input
                    className="form-control"
                    type="number"
                    value={param.lama_investasi}
                    onChange={(e) => handleinputlamaInvest(e)}
                  ></input>
                </div>
                <label htmlFor="formGroupExampleInput2">Jenis Kelamin</label>
                <div>
                  <div className="form-check form-check-inline">
                    <input
                      className="form-check-input"
                      type="radio"
                      checked={param.jenis_kelamin == "Pria"}
                      onChange={(e) => {
                        changeParam("jenis_kelamin", "Pria");
                      }}
                    ></input>
                    <label
                      className="form-check-label"
                      htmlFor="flexRadioDefault1"
                    >
                      Pria
                    </label>
                  </div>
                  <div className="form-check form-check-inline">
                    <input
                      className="form-check-input"
                      type="radio"
                      checked={param.jenis_kelamin == "Wanita"}
                      onChange={(e) => {
                        changeParam("jenis_kelamin", "Wanita");
                      }}
                    ></input>
                    <label
                      className="form-check-label"
                      htmlFor="flexRadioDefault2"
                    >
                      Wanita
                    </label>
                  </div>
                </div>

                <div className="form-group">
                  <label htmlFor="formGroupExampleInput2">Perokok</label>
                  <div>
                    <div className="form-check form-check-inline">
                      <input
                        className="form-check-input"
                        type="radio"
                        checked={param.perokok == "Ya"}
                        onChange={(e) => {
                          changeParam("perokok", "Ya");
                        }}
                      ></input>
                      <label
                        className="form-check-label"
                        htmlFor="flexRadioDefault1"
                      >
                        Ya
                      </label>
                    </div>
                    <div className="form-check form-check-inline">
                      <input
                        className="form-check-input"
                        type="radio"
                        checked={param.perokok == "Tidak"}
                        onChange={(e) => {
                          changeParam("perokok", "Tidak");
                        }}
                      ></input>
                      <label
                        className="form-check-label"
                        htmlFor="flexRadioDefault2"
                      >
                        Tidak
                      </label>
                    </div>
                  </div>
                </div>
                <button
                  type="submit"
                  className="btn btn-primary mb-3"
                  onClick={_onSubmit}
                >
                  Submit
                </button>
              </form>
              {result.length != 0 && (
                <h5 className="card-title">Hasil Perhitungan Investasi</h5>
              )}
              {result.map(function (row, i) {
                return (
                  <div className="card mb-1">
                    <ul className="list-group" key={i}>
                      <li className="list-group-item">Tahun {i + 1}</li>
                      <li className="list-group-item">
                        Awal : Rp. {nf.format(row.Awal)}
                      </li>
                      <li className="list-group-item">
                        Bunga : Rp. {nf.format(row.Bunga)}
                      </li>
                      <li className="list-group-item">
                        Akhir : Rp. {nf.format(row.Akhir)}
                      </li>
                    </ul>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
